from os import system, name
import walka
import time
import sys
import dlcs
import funkcje

def fabulastart():

    funkcje.delay_print("Flexolia, 04.20.1469")
    time.sleep(3)
    #funkcje.clear()
    #print("[Nieznajomy]", end=" "); time.sleep(0.3); funkcje.delay_print("Felix!\n")
    #time.sleep(1)
    #funkcje.clear()
    #print("[Nieznajomy]", end=" "); time.sleep(0.3); funkcje.delay_print("Felix!\n")
    #time.sleep(1)
    #funkcje.clear()
    #print("[Nieznajomy]", end=" "); time.sleep(0.3); funkcje.delay_print("Felix!\n")
    #time.sleep(1)
    #funkcje.clear()
    #print("[Nieznajomy]", end=" "); time.sleep(0.3); funkcje.delay_print("Zbudź się! Nasza wieś została zaatakowana.\n")
    #time.sleep(3.5)
    #funkcje.clear()
    #print("[Nieznajomy]", end=" "); time.sleep(0.3); funkcje.delay_print("Musisz wyruszyć w drogę do zamku króla i poprosić go o pomoc, inaczej\nwszystko stracimy!\n")
    #time.sleep(6)
    #funkcje.clear()
    #print("[Nieznajomy]", end=" "); time.sleep(0.3); funkcje.delay_print("Spotkasz na swojej drodze wielu przeciwników, staraj się stawić im czoła.\n")
    #time.sleep(5)
    #funkcje.clear()
    #print("[Nieznajomy]", end=" "); time.sleep(0.3); funkcje.delay_print("Już czas, ruszaj w imię Flexoli!\n")
    #time.sleep(7)
    funkcje.clear()
    time.sleep(2)

def fabulazakonczenie():
    funkcje.delay_print("Dotarłeś do zamku.\n")
    time.sleep(2)
    funkcje.delay_print("Król wysłał do Twojej wsi oddziały wojska.\n")
    time.sleep(2)
    funkcje.delay_print("Twój dom został ocalony.\n")
    time.sleep(4)
    funkcje.clear()
    print("[Nieznajomy]", end=" "); time.sleep(0.3); funkcje.delay_print("Więc udało Ci się, dzięki Tobie\nnasz dom został ocalony.\n")
    time.sleep(4.5)
    funkcje.clear()
    print("[Nieznajomy]", end=" "); time.sleep(0.3); funkcje.delay_print("Przyszedł czas abyś poznał prawdę o mnie\n")
    time.sleep(4)
    funkcje.clear()
    funkcje.delay_print("*Nieznajomy zdejmuje koc z głowy*\n")
    time.sleep(5)
    funkcje.clear()
    print("[Felix]", end=" "); time.sleep(0.3); funkcje.delay_print("Shrek?!\n")
    time.sleep(2.5)
    funkcje.clear()
    print("[Książe Orków]", end=" "); time.sleep(0.3); funkcje.delay_print("Nie głupcu, przyszły król Orków, Fergus.\n")
    time.sleep(4)

def fabulazlezakonczenie():
    funkcje.delay_print("Nie zdobyłeś wymaganej liczby Punktów Doświadczenia\n")
    time.sleep(1)
    funkcje.delay_print("Nie udało ci się dotrzeć do zamku, twoja wieś została spalona i zrabowana.\n\n")
    time.sleep(1)        
    print(" _      ")      
    print("| |     ")
    print("| |     ")
    print("| |     ")
    print("| |____ ")
    print("|______|")
    time.sleep(4)